.github/workflows/cicd.yml
docs/conf.py

Signed-off-by: Luca Muscariello <lumuscar@cisco.com>

chore: fix release tag

---

docs/_static/js/segment.js
docs/conf.py

Signed-off-by: Luca Muscariello <lumuscar@cisco.com>

feat: add segment support

---

docs/index.rst
docs/pages/dir.md
docs/pages/dir_howto.md
docs/pages/introduction.md
docs/pages/oasf_workflow.md

- **docs: init ads documentation**
- **docs: init ads documentation**
- **docs: init ads documentation**
- **docs: init ads documentation**
- **docs: ads update**
- **docs: ads update**
- **docs: ads update**
- **docs: ads update**

36 documentation dir

---

docs/index.rst
docs/pages/agp-control-plane.md
docs/pages/agp-data-plane.md
docs/pages/agp-security-layer.md
docs/pages/agp-session-layer.md
docs/pages/agp.md

Signed-off-by: Luca Muscariello <lumuscar@cisco.com>

docs: agp update

---

docs/pages/workflow_server_manager.md

feat: added examples to the wfsm tool description

---

docs/pages/semantic_sdk/io_mapper.md

- Add examples of usage with LlamaIndex

chore: update the docs for io mapper

---

docs/pages/csit.md

This PR adds the missing requirements for running tests to the documentation

doc: update CSIT documentation

---

docs/pages/agws/workflow_server_manager.md
docs/pages/dir.md
docs/pages/messaging_sdk/agp-core.md
docs/pages/messaging_sdk/agp-data-plane.md
docs/pages/messaging_sdk/agp-howto.md
docs/pages/messaging_sdk/agp-session-layer.md
docs/pages/semantic_sdk/io_mapper.md
docs/pages/semantic_sdk/semantic_router.md
docs/pages/syntactic_sdk/agntcy_acp_sdk.md
docs/pages/syntactic_sdk/api_bridge_agent.md

chore: docs review

---

docs/pages/agws/workflow_server.rst

Add interrupt support for wfs (langgraph)

chore: update wfs features

---

docs/pages/agws/workflow_server_manager.md

fix: update wfsm docs

---

docs/pages/agws/workflow_server_manager.md

- update doc examples
- add configuration section
- add k8s deployment section

feat: add configuration section for wfsm

---

docs/index.rst
docs/pages/data-model-guide.md

Added a guide on creating agent data model.

feat: add guide on data model

---

docs/pages/hub.md

fix: broken links and cli

---

docs/index.rst
docs/pages/how-to-guides/agents/interrupts.md

acp langgraph interrupts tutorial

docs: acp interrupts tutorial

---

docs/pages/csit.md

Reviewed recent changes to the CSIT docs.

chore: review recent additions

---

docs/pages/agent_directory.md

Fixes to the AGNTCY Agent Directory docs

docs: fixes to AGNTCY Agent Directory docs

---

docs/pages/how-to-guides/agents/thread.rst
docs/pages/how-to-guides/mas-creation-tutorial/mas-tutorial.md
docs/pages/hub.md
docs/pages/messaging_sdk/slim-index.rst

* Also fixes a few error messages from build.

fix: Fix mas howto guide for new manifest models

---

docs/stylesheets/custom.css

Fixes #125 
Removes Agntcy label from the title and the top of the navbar, it's redundant with the logo.
Fixes code blocks background color.
Adds background to selected nav bar item.

fix(styles): CSS alignments to better match AGNTCY colors

---

docs/dir/scenarios.md

Fixing #137 
Added non-interactive signing and verification methods to the Usage Scenarios Directory guide. Also added gRPC error codes and other minor updates.

chore: adding non interactive mode to dir documentation

---

docs/index.md

Hi @natalisucks as discussed via our chat, this is the PR to update our current introduction section. Please let me know if there is any question/comment. 
The team is planning to launch this update tomorrow (July 29th) at 9AM EST. Please let me know if you are able to help us deploy this change. Thank you!

chore: intro section update

---

docs/dir/.index
docs/dir/dir-core-v1-api.md
docs/dir/dir-routing-v1-api.md
docs/dir/dir-search-v1-api.md
docs/dir/dir-sign-v1-api.md
docs/dir/dir-store-v1-api.md

Added API reference for directory generated from proto files using protoc-gen-doc.

feat: added api reference for directory

---

docs/index.md

fix(docs): typo fixed

---

.github/scripts/requirements.txt

- **docs(ci): add requirements.txt and update workflow to use it for dependencies**
- **ci: restrict workflow to docs and mkdocs folders**
- **ci: add beautifulsoup4 to requirements.txt for bs4 import**

251 docs cicd job to collecgt stats
